site_name: RHUL ATLAS PhD Tutorials

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
nav:
  - Home: index.md
  - Example Tutorial: example.md
  - MadGraph5_aMC@NLO: madgraph.md